### ISSUE TITLE
Format conversion doesn't seem to work`

### ISSUE THREAD

**Issue by wilg** [jruby/image_voodoo#18]
Given this PNG input image:

<img width="242" alt="test" src="https://cloud.githubusercontent.com/assets/54353/23682833/9329913a-034a-11e7-9b8c-78668635c1f1.png">

and this code: 

```rb
ImageVoodoo.with_image("test.png").bytes("JPG")
```

Results in this broken file:

![out](https://cloud.githubusercontent.com/assets/54353/23682849/a4f22e04-034a-11e7-8c9a-3df8610d0507.jpg)

Am I just doing something wrong here?

```rb
ImageVoodoo.with_bytes(ImageVoodoo.with_image("test.png").bytes("JPG")).format
```

returns JPG as expected

**Comment by enebo** [comment]
No obvious answer yet (although I recently switched to Linux and I am realizing OpenJDK does not have JAI bundled in it :| ):

http://stackoverflow.com/questions/3432388/imageio-not-able-to-write-a-jpeg-file

The colorspace comments makes me think there is some code I need to add when translation is from a png to a jpg (although I have done this tons of times so I don't get why it happens here).

**Comment by enebo** [comment]
Hmm here is another article pointing out in the answer it is a bug in Java which has never really been fixed: 

http://stackoverflow.com/questions/13072312/jpeg-image-color-gets-drastically-changed-after-just-imageio-read-and-imageio

Wow if we need to do this to fix this then there may be issues since I will need to load some Java code.

**Comment by wilg** [comment]
FWIW here's `java -version`:

```
› java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

**Comment by wilg** [comment]
Looks like it maybe just needs to be converted to an RGB image first?

http://stackoverflow.com/a/2408779/813265

**Comment by wilg** [comment]
Well, actually it seems like `bytes` is writing RGB data to a CMYK jpeg file.

**Comment by wilg** [comment]
Looks like there's a possibly relevant PR: https://github.com/jruby/image_voodoo/pull/9
